name: "Build OpenWRT Installer ISO"
author: "sirpdboy"
description: "Convert OpenWRT IMG to bootable auto-installer ISO"
branding:
  icon: 'package'
  color: 'green'

inputs:
  INPUT_IMG:
    description: "Path to OpenWRT IMG file"
    required: false
    default: "/mnt/openwrt.img"
  OUTPUT_DIR:
    description: "Output directory for ISO file"
    required: false
    default: "/output"
  OUTPUT_ISO_NAME:
    description: "Name of output ISO file"
    required: false
    default: "openwrt-autoinstall.iso"

runs:
  using: "composite"
  steps:
    - name: Checkout action repository files
      shell: bash
      run: |
        echo "Copying required scripts..."
        if [ -f "${{ github.action_path }}/docker-build.sh" ]; then
          cp "${{ github.action_path }}/docker-build.sh" ./docker-build.sh
          chmod +x ./docker-build.sh
        fi
        if [ -f "${{ github.action_path }}/build.sh" ]; then
          cp "${{ github.action_path }}/build.sh" ./build.sh
          chmod +x ./build.sh
        fi
        
    - name: Setup
      shell: bash
      run: |
        echo "🚀 OpenWRT ISO Builder"
        echo "======================"
        echo "Input IMG: ${{ inputs.INPUT_IMG }}"
        echo "Output Dir: ${{ inputs.OUTPUT_DIR }}"
        echo "ISO Name: ${{ inputs.OUTPUT_ISO_NAME }}"
        echo ""
        # ls -la ./
    - name: Run Docker Build
      shell: bash
      run: |
        if [ ! -f "./docker-build.sh" ]; then
          echo "❌ docker-build.sh not found!"
          echo "Current directory contents:"
          ls -la
          exit 1
        fi
        
        # 执行Docker构建
        ./docker-build.sh \
          "${{ inputs.INPUT_IMG }}" \
          "${{ inputs.OUTPUT_DIR }}" \
          "${{ inputs.OUTPUT_ISO_NAME }}"
