name: "Build OpenWRT Installer ISO"
author: "sirpdboy"
description: "Convert OpenWRT IMG to bootable auto-installer ISO"
branding:
  icon: 'package'
  color: 'green'

inputs:
  INPUT_IMG:
    description: "Path to OpenWRT IMG file"
    required: false
    default: "/mnt/openwrt.img"
  OUTPUT_DIR:
    description: "Output directory for ISO file"
    required: false
    default: "/output"
  OUTPUT_ISO_NAME:
    description: "Name of output ISO file"
    required: false
    default: "openwrt-autoinstall.iso"

runs:
  using: "composite"
  steps:
    - name: Setup
      shell: bash
      run: |
        echo "ðŸš€ OpenWRT ISO Builder"
        echo "======================"
        echo "Input IMG: ${{ inputs.INPUT_IMG }}"
        echo "Output Dir: ${{ inputs.OUTPUT_DIR }}"
        echo "ISO Name: ${{ inputs.OUTPUT_ISO_NAME }}"
        echo ""
        
        # ç¡®ä¿è„šæœ¬å¯æ‰§è¡Œ
        chmod +x ./dockerrun.sh 2>/dev/null || true
        
    - name: Run Docker Build
      shell: bash
      run: |
        # æ‰§è¡ŒDockeræž„å»º
        ./dockerrun.sh \
          "${{ inputs.INPUT_IMG }}" \
          "${{ inputs.OUTPUT_DIR }}" \
          "${{ inputs.OUTPUT_ISO_NAME }}"
